name: MoRuneSocketing
version: 1.0.5-Release
author: MoRune
main: com.morunesocketing.MoRuneSocketing
api-version: 1.13

commands:
  mrs:
    description: MoRuneSocketing main command
    usage: /mrs <subcommand>
    aliases: [rune]
    tab-completer: com.morunesocketing.RuneCommand

permissions:
  morunesocketing.use:
    description: Allows using basic commands
    default: true
  morunesocketing.open:
    description: Allows opening menus
    default: true
  morunesocketing.admin:
    description: Allows admin commands
    default: op
